apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: sso
spec:
  interval: 5m
  dependsOn:
    - name: keycloak
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-secret
    extraArgs:
      oidc-issuer-url: "https://sso.triqster.eu/auth/realms/master"
      provider: "oidc"
      set-authorization-header: "true"
      show-debug-on-error: "true"
      skip-provider-button: "true"
      whitelist-domain: ".triqster.eu"
    image:
      repository: jonkerj/oauth2-proxy
      tag: master
    ingress:
      enabled: true
      path: /oauth2
      hosts:
      - dashboard.triqster.eu
      - kubeview.triqster.eu
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
