apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:1JcG8Jmi2hw=,iv:8vOo76/TnXz/aZ4vUYjhHbWilbZPBZ0eczzLoefisrE=,tag:+J+HBxc9sFBvT2Qb7CQ10Q==,type:str]
    client-secret: ENC[AES256_GCM,data:ooCx6LcfAXaGb+RC6GvoAsTNJQ9dOVIayZ/7q7jr2qAnOzRLTdudXPuF8q+oIgZS,iv:IACBZquIPAjL9u58wGMcl5D8sSZB1UdhOy4gyA867qE=,tag:7jmrw7MHOiZLdh9A/6YcJw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:xflfduKbm8JjfiR0GNEQDvVYX6BOfYezuMd4+s241Pk=,iv:GQqTIMiNU71tCmtWkEAzpEJ9UTFFPsoqAzrGFejLaB0=,tag:6W/W+tE7MAWmiJV5/zMdEg==,type:str]
kind: Secret
metadata:
    name: oauth2-secret
    namespace: sso
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-28T13:53:51Z"
    mac: ENC[AES256_GCM,data:xEXlZd+6TYw1tWDlruXU84QSeAaFZ/3/2kdM0yUeU9at5jsDPO04iSWWTLHm0gFd+edMzn8vBDKD28hh8tovefHJorV44PJC8UOmNfK8vFJ+6WveAdT4AF2XCXKX8TPjE1wsHVk4Xsb3gnqswXj407EnahhV2CSd6dVGXT8XAGA=,iv:Z711sQxkaffqO8MB6xKSdN1XSfWhdukVso1u1opD5Jc=,tag:JmcWyfyux8zT7DL2nBMzrA==,type:str]
    pgp:
        - created_at: "2021-03-28T13:53:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7z3cIrxPhdPAQ/+I2w2C/UjOxCFhXuoiN2b6lZIkXgTqnNcZyR2TZpYDP6g
            12PHa4RQHSJP4qdXqkRLaQwdOYDtLtjFCnNI3IlKpEcFr+H6bkJ6mwb3a8U4S3U3
            AZAqxghFbgjz35GQVcSk4d1gqdwDvVg6AfH5gAsCAbOe8bGJYAVx5BnGFsyiQVez
            P3v4mLb+WlMWKno04jy+dQiJOn1+HkEPMyWcYcny8sSqKvgTUItZtOlzOlaGZ3qU
            4P7hGVd3No7HW7ed76oxvoK/4tHrXQSUyuikkTTHgMO4kVWgIZl9h9iSd5hrcvLX
            YGnA3FHsloe1g/K5XYuLCjXnffp+b25oz5x63HcX3Yx9d+5zWaziG7y0iNgVq6fN
            e0UODt1ceKR9JknWSOZ1skh3HUP+Xc87hsCbICoeowDjsXMZc3ff9sL0nF6lAn7x
            7uisH7Vr2FSJ38bqqMZlXJ7JO3OeI7+LibfeMt+til2RqL4bvsuWkWEIoT81D04C
            +dWTYK+1f7Zk2jkuTC1U5FZ/4F9900f+PD6pJIBnbMVlrs+pNNuh98iA+S3Uyr9C
            r4z6ulu5sB5yzbCPXho4v3LiseEmIxn9co9FyJtQEhaM7BSY63JahHesvXXc5wBp
            u+Zn4dA4SYppeQbS7uSLprfOjuevQmu2RL7Gpod9/vLijXSIas449XxptK4sKD3S
            XAEgilZA0+GwC8/TwMpAArce1aEYDbABgBjMd9Atgi+/w6CeWdAobxHuU0A+sfJK
            32+17gDTF5N0hczEepLQdfvQuvYwdAEzlMbdh3qlGfV/JqBQRXzylAKAtW+h
            =ji/G
            -----END PGP MESSAGE-----
          fp: B2E3944C452881488949063870EE7A2B58565AFE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
