---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitwarden-rs
  namespace: flux-system
spec:
  url: https://skeen.github.io/helm-bitwarden_rs
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bitwarden-rs
  namespace: flux-system
spec:
  url: https://github.com/jonkerj/helm-bitwarden_rs
  interval: 1h
