---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeview
  namespace: kubeview
spec:
  interval: 1m
  chart:
    spec:
      chart: kubeview
      version: 0.1.20
      sourceRef:
        kind: HelmRepository
        name: kubeview
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-response-headers: authorization
        nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
      hosts:
        - host: kubeview.triqster.eu
          paths: ['/']
      tls:
        - hosts: ['kubeview.triqster.eu']
          secretName: kubeview-tls
