---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.5
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    nfs:
      path: /mnt/tank/nfs/k8s
      server: 192.168.4.50
      mountOptions:
      - noatime
      - async
    storageClass:
      archiveOnDelete: false
      defaultClass: true
      name: nfs
    resources:
      requests:
        cpu: 50m
        memory: 16Mi
      limits:
        cpu: 250m
        memory: 64Mi
