---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  url: https://charts.helm.sh/stable
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: storage
spec:
  interval: 1m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: "1.2.11"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
      interval: 1m
  values:
    nfs:
      path: /mnt/tank/nfs/k8s 
      server: 192.168.4.50
      mountOptions:
      - nfsvers=4.0
    storageClass:
      archiveOnDelete: false
      defaultClass: true
      name: nfs
    resources:
      requests:
        cpu: 50m
        memory: 16Mi
      limits:
        cpu: 250m
        memory: 64Mi
