---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.5.9
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
