---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.25.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicaCount: 3
      config:
        use-proxy-protocol: "true"
      extraArgs:
        enable-ssl-passthrough: ''
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 150Mi
        limits:
          cpu: 2
          memory: 500Mi
    defaultBackend:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 10m
          memory: 20Mi
