apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m
  path: "./cert-manager/issuer/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: cert-manager-crd
  - name: cert-manager-app
