apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  interval: 10m
  path: "./cert-manager/app/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: cert-manager-crd
  healthChecks:
  - kind: Deployment
    name: cert-manager
    namespace: cert-manager
    apiVersion: apps/v1
  - kind: Deployment
    name: cert-manager-webhook
    namespace: cert-manager
    apiVersion: apps/v1
